local seed = {
	["Bovina"] = {name = "None", set=false},
	["Golden_Goliath"] = {name = "None", set=false},
	["Ssslumber"] = {name = "JRL_Mumbo_Found", set=false},
	["MT_Kickball"] = {name = "None", set=false},
	["Relic_Thingy"] = {name = "None", set=false},
	["Top_Of_Temple"] = {name = "WW_Mumbo_Found", set=false},
	["Slightly_Sacred_Chamber"] = {name = "None", set=false},
	["Targitzan"] = {name = "Hatch_Found", set=false},
	["Swamp"] = {name = "Sack_Pack_Found", set=false},
	["Pillars"] = {name = "None", set=false},
	["Dilberta"] = {name = "None", set=false},
	["Ordnance_Storage"] = {name = "None", set=false},
	["Crushing_Shed"] = {name = "NestKing_Found", set=false},
	["Old_King_Coal"] = {name = "None", set=false},
	["Generator_Cavern"] = {name = "TDL_Mumbo_Found", set=false},
	["Power_Hut"] = {name = "None", set=false},
	["Waterfall_Cavern"] = {name = "Wing_Whack_Found", set=false},
	["Flooded_Caves"] = {name = "Airborne_Found", set=false},
	["Canary_Mary_1"] = {name = "Fire_Eggs_Found", set=false},
	["Small_Waterfall"] = {name = "Grip_Grab_Found", set=false},
	["Cactus_of_Strength"] = {name = "None", set=false},
	["Dive_of_Death"] = {name = "None", set=false},
	["Top_Of_Inferno"] = {name = "None", set=false},
	["Hoop_Hurry"] = {name = "None", set=false},
	["Balloon_Burst"] = {name = "None", set=false},
	["Saucer_of_Peril"] = {name = "None", set=false},
	["Star_Spinner"] = {name = "None", set=false},
	["Dodgem_Dome"] = {name = "None", set=false},
	["Patch"] = {name = "None", set=false},
	["Boggys_Kids"] = {name = "None", set=false},
	["Pawno"] = {name = "None", set=false},
	["Chris_P_Bacon"] = {name = "Talon_Torpedo_Found", set=false},
	["Seemee_Fish"] = {name = "None", set=false},
	["Aliens"] = {name = "None", set=false},
	["Merry_Maggie"] = {name = "None", set=false},
	["Sub_Minigame"] = {name = "None", set=false},
	["Lord_Woo_Fak_Fak"] = {name = "None", set=false},
	["Tiptup"] = {name = "None", set=false},
	["Smugglers_Cavern"] = {name = "Snooze_Pack_Found", set=false},
	["Pig_Pool"] = {name = "None", set=false},
	["Terry"] = {name = "None", set=false},
	["Terry_Nest"] = {name = "None", set=false},
	["Chompa"] = {name = "IoH_Mumbo_Found", set=false},
	["Rocknuts_Jiggy"] = {name = "GI_Mumbo_Found", set=false},
	["Roar_Cage"] = {name = "None", set=false},
	["Oogle_Boogles"] = {name = "None", set=false},
	["Terrys_Kids"] = {name = "None", set=false},
	["Stomping_Plains"] = {name = "None", set=false},
	["Styrac_Family"] = {name = "None", set=false},
	["Dippy"] = {name = "None", set=false},
	["Trash_Compactor"] = {name = "None", set=false},
	["Twinklies_Packing"] = {name = "None", set=false},
	["Weldar"] = {name = "None", set=false},
	["Quality_Control"] = {name = "Stony_Found", set=false},
	["Clinkers_Cavern"] = {name = "None", set=false},
	["Attic"] = {name = "None", set=false},
	["Workers_Jiggy"] = {name = "None", set=false},
	["Toxic_Waste_Pool"] = {name = "None", set=false},
	["Tintops"] = {name = "None", set=false},
	["Toxic_Waste_Box"] = {name = "None", set=false},
	["Ice_Wall"] = {name = "None", set=false},
	["HFP_Kickball"] = {name = "Bill_Drill_Found", set=false},
	["Colosseum"] = {name = "None", set=false},
	["Volcano"] = {name = "HFP_Mumbo_Found", set=false},
	["Boggys_Fish"] = {name = "None", set=false},
	["Dragon_Brothers"] = {name = "None", set=false},
	["Sabreman"] = {name = "Glide_Found", set=false},
	["Alien_Kids"] = {name = "Sub_Found", set=false},
	["Oil_Drill"] = {name = "None", set=false},
	["Ice_Train"] = {name = "None", set=false},
	["Pot_O_Gold"] = {name = "Snowball_Found", set=false},
	["Trash_Can"] = {name = "Springy_Step_Shoes_Found", set=false},
	["Mingy_Jongo"] = {name = "None", set=false},
	["Canary_Mary_3"] = {name = "SuperBanjo_Found", set=false},
	["Eyeball_Plants"] = {name = "None", set=false},
	["Zubbas"] = {name = "None", set=false},
	["Superstash"] = {name = "None", set=false},
	["Jelly_Castle"] = {name = "None", set=false},
	["Cheese_Wedge"] = {name = "None", set=false},
	["Mr_Fit"] = {name = "None", set=false},
	["King_Jingaling"] = {name = "Split_Up_Found", set=false},
	["White_Jinjos"] = {name = "None", set=false},
	["Orange_Jinjos"] = {name = "Goggles_Found", set=false},
	["Yellow_Jinjos"] = {name = "None", set=false},
	["Brown_Jinjos"] = {name = "None", set=false},
	["Green_Jinjos"] = {name = "None", set=false},
	["Red_Jinjos"] = {name = "None", set=false},
	["Blue_Jinjos"] = {name = "None", set=false},
	["Purple_Jinjos"] = {name = "Double_Air_Found", set=false},
	["Black_Jinjos"] = {name = "None", set=false},
	["Cheato Page: MT: Snake Heads"] = {name = "Washing_Machine_Found", set=false},
	["Cheato Page: MT: Prison Compound"] = {name = "None", set=false},
	["Cheato Page: MT: Jade Snake Grove"] = {name = "None", set=false},
	["Cheato Page: GGM: Canary Mary Race"] = {name = "None", set=false},
	["Cheato Page: GGM: Level Entrance"] = {name = "None", set=false},
	["Cheato Page: GGM: Water Storage"] = {name = "None", set=false},
	["Cheato Page: WW: Haunted Cavern"] = {name = "None", set=false},
	["Cheato Page: WW: The Inferno (Van)"] = {name = "None", set=false},
	["Cheato Page: WW: Saucer of Peril"] = {name = "None", set=false},
	["Cheato Page: JRL: Pawno's"] = {name = "GGM_Mumbo_Found", set=false},
	["Cheato Page: JRL: Seemee"] = {name = "None", set=false},
	["Cheato Page: JRL: Ancient Swimming Baths"] = {name = "None", set=false},
	["Cheato Page: TDL: Dippy's Pool"] = {name = "None", set=false},
	["Cheato Page: TDL: Inside the Mountain"] = {name = "None", set=false},
	["Cheato Page: TDL: Boulder"] = {name = "None", set=false},
	["Cheato Page: GI: Loggo"] = {name = "None", set=false},
	["Cheato Page: GI: Floor 2"] = {name = "None", set=false},
	["Cheato Page: GI: Repair Depot"] = {name = "None", set=false},
	["Cheato Page: HFP: Lava Side"] = {name = "None", set=false},
	["Cheato Page: HFP: Icicle Grotto"] = {name = "None", set=false},
	["Cheato Page: HFP: Icy Side"] = {name = "None", set=false},
	["Cheato Page: CCL: Canary Mary"] = {name = "Beak_Bayonet_Found", set=false},
	["Cheato Page: CCL: Pot o' Gold"] = {name = "Dragon_Kazooie_Found", set=false},
	["Cheato Page: CCL: Zubbas' Nest"] = {name = "Leg_Spring_Found", set=false},
	["Cheato Page: Spiral Mountain"] = {name = "Van_Found", set=false},
	["Honeycomb: MT: Entrance"] = {name = "Subaqua_Found", set=false},
	["Honeycomb: MT: Bovina"] = {name = "Grenade_Eggs_Found", set=false},
	["Honeycomb: MT: Treasure Chamber"] = {name = "None", set=false},
	["Honeycomb: GGM: Boulder (Toxic Gas Cave)"] = {name = "Clockworks_Found", set=false},
	["Honeycomb: GGM: Boulder"] = {name = "JiggyWiggySpecial_Found", set=false},
	["Honeycomb: GGM: Train Station"] = {name = "Dinosaur_Found", set=false},
	["Honeycomb: WW: Space Zone"] = {name = "None", set=false},
	["Honeycomb: WW: Mumbo's Skull"] = {name = "None", set=false},
	["Honeycomb: WW: Crazy Castle Area"] = {name = "None", set=false},
	["Honeycomb: JRL: Seemee"] = {name = "None", set=false},
	["Honeycomb: JRL: Atlantis"] = {name = "None", set=false},
	["Honeycomb: JRL: Waste Pipe"] = {name = "Bee_Found", set=false},
	["Honeycomb: TDL: Central Area"] = {name = "Taxi_Pack_Found", set=false},
	["Honeycomb: TDL: Styracosaurus Family Cave"] = {name = "None", set=false},
	["Honeycomb: TDL: River Passage"] = {name = "None", set=false},
	["Honeycomb: GI: Floor 3"] = {name = "Claw_Clambers_Found", set=false},
	["Honeycomb: GI: Train Station"] = {name = "None", set=false},
	["Honeycomb: GI: Chimney"] = {name = "Pack_Whack_Found", set=false},
	["Honeycomb: HFP: Inside the Volcano"] = {name = "None", set=false},
	["Honeycomb: HFP: Train Station"] = {name = "None", set=false},
	["Honeycomb: HFP: Lava Side"] = {name = "None", set=false},
	["Honeycomb: CCL: Underground"] = {name = "None", set=false},
	["Honeycomb: CCL: Trash Can"] = {name = "None", set=false},
	["Honeycomb: CCL: Pot o' Gold"] = {name = "None", set=false},
	["Honeycomb: IoH: Plateau"] = {name = "None", set=false},
	["Glowbo: MT: Mumbo's Skull"] = {name = "None", set=false},
	["Glowbo: MT: Behind Wumba's Wigwam"] = {name = "None", set=false},
	["Glowbo: GGM: Near Entrance"] = {name = "CCL_Mumbo_Found", set=false},
	["Glowbo: GGM: Mine Entrance 2"] = {name = "None", set=false},
	["Glowbo: WW: The Inferno"] = {name = "None", set=false},
	["Glowbo: WW: Inside Wumba's Wigwam"] = {name = "None", set=false},
	["Glowbo: JRL: Pawno's Emporium"] = {name = "MT_Mumbo_Found", set=false},
	["Glowbo: JRL: Under Wumba's Wigwam"] = {name = "Breegull_Blaster_Found", set=false},
	["Glowbo: TDL: Near Unga Bunga's Cave Entrance"] = {name = "Shack_Pack_Found", set=false},
	["Glowbo: TDL: Behind Mumbo's Skull"] = {name = "HoneyBack_Found", set=false},
	["Glowbo: GI: Floor 2"] = {name = "None", set=false},
	["Glowbo: GI: Floor 3"] = {name = "None", set=false},
	["Glowbo: HFP: Lava Side"] = {name = "Detonator_Found", set=false},
	["Glowbo: HFP: Icy Side"] = {name = "Ice_Eggs_Found", set=false},
	["Glowbo: CCL: Overworld (Underwater)"] = {name = "None", set=false},
	["Glowbo: CCL: Central Cavern (Underwater)"] = {name = "None", set=false},
	["Glowbo: IoH: Cliff Top"] = {name = "Egg_Aim_Found", set=false},
	["Jinjo_MT_Jade_Snake_Grove"] = {name = "None", set=false},
	["Jinjo_MT_Kickball"] = {name = "None", set=false},
	["Jinjo_MT_Temple"] = {name = "None", set=false},
	["Jinjo_MT_Pool"] = {name = "None", set=false},
	["Jinjo_MT_Bridge"] = {name = "None", set=false},
	["Jinjo_GGM_JRL_Pipe"] = {name = "None", set=false},
	["Jinjo_GGM_Jail_Cell"] = {name = "None", set=false},
	["Jinjo_GGM_Toxic_Gas_Cave"] = {name = "None", set=false},
	["Jinjo_GGM_Under_Boulder"] = {name = "None", set=false},
	["Jinjo_GGM_Minecart_Rails"] = {name = "None", set=false},
	["Jinjo_WW_Big_Top"] = {name = "None", set=false},
	["Jinjo_WW_Cave_of_Horrors"] = {name = "None", set=false},
	["Jinjo_WW_Area_51"] = {name = "None", set=false},
	["Jinjo_WW_Dodgems_Dome"] = {name = "None", set=false},
	["Jinjo_WW_Cactus"] = {name = "None", set=false},
	["Jinjo_JRL_Alcove"] = {name = "None", set=false},
	["Jinjo_JRL_Blubbers"] = {name = "None", set=false},
	["Jinjo_JRL_Big_Fish"] = {name = "None", set=false},
	["Jinjo_JRL_Seaweed_Sanctum"] = {name = "None", set=false},
	["Jinjo_JRL_Chest"] = {name = "None", set=false},
	["Jinjo_TDL_Caged_Underwater"] = {name = "None", set=false},
	["Jinjo_TDL_Near_Entrance"] = {name = "None", set=false},
	["Jinjo_TDL_Caged_Near_Unga"] = {name = "None", set=false},
	["Jinjo_TDL_Trex_Switch"] = {name = "None", set=false},
	["Jinjo_TDL_Stomping_Plains"] = {name = "None", set=false},
	["Jinjo_GI_Floor_5"] = {name = "None", set=false},
	["Jinjo_GI_Floor_2"] = {name = "None", set=false},
	["Jinjo_GI_JRL_Pipe"] = {name = "None", set=false},
	["Jinjo_GI_Floor_3"] = {name = "None", set=false},
	["Jinjo_GI_Outside"] = {name = "None", set=false},
	["Jinjo_HFP_Waterfall"] = {name = "None", set=false},
	["Jinjo_HFP_Pool"] = {name = "None", set=false},
	["Jinjo_HFP_Icy_Tunnel"] = {name = "None", set=false},
	["Jinjo_HFP_Icicle_Grotto"] = {name = "None", set=false},
	["Jinjo_HFP_Mildred"] = {name = "None", set=false},
	["Jinjo_CCL_Trash_Can"] = {name = "None", set=false},
	["Jinjo_CCL_Cheese_Wedge"] = {name = "None", set=false},
	["Jinjo_CCL_Central_Cavern"] = {name = "None", set=false},
	["Jinjo_CCL_Mingy"] = {name = "None", set=false},
	["Jinjo_CCL_Wumbas_Wigwam"] = {name = "None", set=false},
	["Jinjo_IOH_Wooded_Hollow"] = {name = "None", set=false},
	["Jinjo_IOH_Wasteland"] = {name = "None", set=false},
	["Jinjo_IOH_Cliff_Top"] = {name = "None", set=false},
	["Jinjo_IOH_Plateau"] = {name = "None", set=false},
	["Jinjo_SM_Waterfall"] = {name = "None", set=false},
};

return seed;